#!/bin/bash
#
#  ▄▄▄▄· ▪  ▄▄▄▄· 
#  ▐█ ▀█▪██ ▐█ ▀█▪
#  ▐█▀▀█▄▐█·▐█▀▀█▄
#  ██▄▪▐█▐█▌██▄▪▐█
#  ·▀▀▀▀ ▀▀▀·▀▀▀▀ 
#  stupid pip script

# shellcheck disable=2155

usage() {
    echo
    echo "usage:"
    echo "    bib outdated"
    echo "    bib path [<version>]"
    echo "    bib cat  [<version>]"
    echo "    bib add <pkg> [<version>]"
    echo "    bib del <pkg> [<version>]"
    echo "    bib help | --help | -h"
    echo
    exit "$1"
}

main() {
    case "$1" in
        help|--help|-h)
            usage 0
            ;;
        path)
            echo ~/.bib/"$(get_version "$2")"
            ;;
        cat)
            cat ~/.bib/"$(get_version "$2")" 2> /dev/null
            ;;
        outdated) shift; outdated "$@" ;;
        add)      shift; add "$@" ;;
        del)      shift; del "$@" ;;
        *)        usage 1 ;;
    esac
}

init() {
    mkdir -p ~/.bib
    touch ~/.bib/"$1"
}

get_version() {
    if [ "$1" = '' ]; then
        pyenv version-name || python -c 'import platform;print(platform.python_version())'
    else
        echo "$1"
    fi
}

outdated() {
    local version=$(get_version "$1")
    init "$version"
    comm <(pip list --outdated | tail +3 | cut -d ' ' -f1 | sort) \
         <(sort -u ~/.bib/"$version") \
         -12
}

remove_line_in_file() {
    local contents=$(
        sort -u "$2" | while read -r line; do
            [ "$line" = '' ] && continue
            [ "$line" != "$1" ] && echo "$line"
        done
        )
    if [ "$contents" = '' ]; then
        echo -n '' > "$2"
    else
        echo -n "$contents" > "$2"
    fi
}

del() {
    local pkg=$1
    local version=$(get_version "$2")

    [ "$pkg" = "" ] && usage 1

    init "$version"
    local file=~/.bib/"$version"
    local tmpfile

    {
        # this is transactional, avoid nuking
        # ~/.bib/... if something goes wrong
        tmpfile=$(mktemp) \
            && cp "$file" "$tmpfile" \
            && remove_line_in_file "$pkg" "$tmpfile" \
            && mv "$tmpfile" "$file"
    } || rm "$tmpfile"
}

add() {
    local pkg=$1
    local version=$(get_version "$2")

    [ "$pkg" = "" ] && usage 1

    init "$version"

    # check if the package is already present
    # if yes then don't do anything
    if [ "$(echo "$pkg" | comm - <(cat ~/.bib/"$version") --nocheck-order -12)" = "" ]; then
        echo "$pkg" >> ~/.bib/"$version"
    fi
}

main "$@"
